server:
  port: 1003

spring:
  profiles:
    active: dev

  application:
    name: eureka-client-provider
#指向eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/