server:
  port: 1003

spring:
  profiles:
    active: dev
  cloud:
    nacos:  #配置Nacos的地址
      server-addr: localhost:8848

  application:
    name: nacos-client-provider
##指向eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:1001/eureka/

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
