server:
  port: 1002

spring:
  profiles:
    active: dev

  application:
    name: eureka-client-consumer
  cloud:
    zookeeper:
      connect-string: localhost:2181
#指向eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:1001/eureka/