server:
  port: 1002

spring:
  profiles:
    active: dev

  application:
    name: eureka-client-consumer
#指向eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
#新版本feign默认关闭，此处必须开启
feign:
  circuitbreaker:
    enabled: true