server:
  port: 1006
eureka:
  instance:
    #每隔5s发送一次心跳
    lease-renewal-interval-in-seconds: 5
    #告知服务端10秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 10
  client:
    #默认为30秒
    registry-fetch-interval-seconds: 5
    serviceUrl:
      #eureka注册中心地址
      defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能
          enabled: true
          #使用小写服务名，默认是大写
          lower-case-service-id: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  file:
    path: D:/project/spring-boot-cloud/gateway-service