server:
  port: 1006

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能
          enabled: true
          #使用小写服务名，默认是大写
          lower-case-service-id: true
      routes:
        - id: iaas-service_router
          uri: lb://iaas-service
          predicates:
            - Path=/user/info
      #          filters:
      #            - StripPrefix=1

  application:
    name: nacos-client-consumer


logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
