server:
  port: 1006

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能
          enabled: true
          #使用小写服务名，默认是大写
          lower-case-service-id: true
      routes:
        - id: iaas-service_router
#          负载到iaas-service服务
          uri: lb://iaas-service
          predicates:
#              拦截路径
            - Path=/user/info
      #          filters:
#                    去除路径 eg：iaas-service/user/info -》 iaas-service/info
      #            - StripPrefix=1
        - id: nacos-client-consumer_router
            #          负载到iaas-service服务
          uri: lb://nacos-client-consumer
          predicates:
              #              拦截路径
            - Path=/like

      #    网关限流规则配置
    sentinel:
      filter:
        enabled: true
      transport:
        dashboard: localhost:8080
#        限流配置文件保存到nacos方便实时更新
      datasource:
        #[
        #  {
        #    "resource": "nacos-client-consumer_router",
        #    "resourceMode": 0 ,
        #    "count": 5,
        #    "intervalSec": 60
        #  },
        #  {
        #    "resource": "nacos-client-consumer-api",
        #    "resourceMode":"1",
        #    "count": 1,
        #    "intervalSec": 60
        #  }
        #]
          ds1.nacos:
            server-addr: localhost:8848
            dataId: gw-flow
            ruleType: gw_flow
            #[
              #  {
              #    "apiName": "nacos-client-consumer-api",
              #    "predicateItems": [
              #      {
              #        "pattern": "/like"
              #      }
              #    ]
            #  }
            #]
          ds2.nacos:
            server-addr: localhost:8848
            dataId: api-group
            ruleType: gw_api_group
  application:
    name: gateway-service


logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
