server:
  port: 1001

spring:
  profiles:
    active: dev

  application:
    name: eureka-server

eureka:
  instance:
    hostname: 127.0.0.1
  #禁止注册自己
  client:
    #关闭eureka的客户端行为:注册服务
    register-with-eureka: false
    #关闭eureka的客户端行为:订阅服务
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1001/eureka/